### PR TITLE
Add support for Mosquitto version >=2.x and arm(v7 and 64) to Dockerfile

### LINKED ISSUE #91: undefined reference to `mosquitto_client_id'
I'm trying to install it on raspberry pi, but i get this:

```
pi@raspberrypi:~/go/src/mosquitto-go-auth $ make
go build -buildmode=c-archive go-auth.go
go build -buildmode=c-shared -o go-auth.so
# github.com/iegomez/mosquitto-go-auth
/usr/bin/ld: $WORK/b001/_x003.o: in function `mosquitto_auth_acl_check':
auth-plugin.c:(.text+0x3ec): undefined reference to `mosquitto_client_id'
/usr/bin/ld: auth-plugin.c:(.text+0x3f8): undefined reference to `mosquitto_client_username'
collect2: error: ld returned 1 exit status
make: *** [Makefile:3: all] Error 2

```
can you help me out of this, thank you

### PR DESCRIPTION
**Pull request by arctic-alpaca**
Hi,
I created a Dockerfile which seems to work with Mosquitto 1.6.14 and 2.0.9 on armv7, (arm64, untested) and amd64 and should fix #91. The Dockerfile currently uses `unresolved-symbols=ignore-all` for every architecture. This could be changed as suggested in this  https://github.com/iegomez/mosquitto-go-auth/issues/91#issuecomment-727036007. I only tested the resulting containers for starting with no errors on a Raspberry Pi 3B and a WSL2 Debian system.

To support Mosquitto versions from 2.x up, libwebsockets needs to be built from source since the Debian supplied version is too old.

The Dockerfile is based on [Docker buildx](https://docs.docker.com/buildx/working-with-buildx/) and can't be built without it. This is only relevant for building and doesn't impact running the container.

I also created [a workflow](https://github.com/arctic-alpaca/mosquitto-go-auth-multiarch/blob/main/.github/workflows/create_containers.yml) for GitHub Actions to automatically check out the latest release of this plugin, create containers for armv7, arm64 and and64 and publish them to DockerHub. If you are interested in using GitHub Actions to automatically create your Docker containers, I can assist in getting it running.

### CODE REVIEW

**Comment by iegomez** [comment]
Hi, @arctic-alpaca! Sorry for not responding earlier, I've not dedicated any time to the plugin the week.
I have an ongoing PR to ump versions, I'll check and test yours and whatever diff may come so we can decide which one should go in first.

Thanks for your contribution!

Cheers!

**Comment by iegomez** [comment]
Hey, @arctic-alpaca! I checkedout your branch to test it locally before merging so I could go ahead with my PR which was only missing building `libwebsockets` from source, but I hit this issue:
```
Removing intermediate container c1863e4df8f6
 ---> 6a99ea43edd5
Step 11/33 : FROM --platform=$BUILDPLATFORM golang:latest AS go_auth_builder
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
```
Do you happen to know anything about it?

**Comment by arctic-alpaca** [comment]
I'm not sure what's happening but I suspect it might be related to buildx's target platform flag. Could you share what command you used?

I think something like `docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 .` should work. I'll check when I'm back at my computer.

**Comment by iegomez** [comment]
@arctic-alpaca I just tried with simple `docker build .` and was able to reproduce the same result. 
Now I see that to your change needs `dockerx` to be built, and `docker buildx build -t mosquitto-go-auth .` does build the image correctly. I'm not sure about the implications of demanding `buildx` as the default since it's not readily available in every platform without user action (https://docs.docker.com/buildx/working-with-buildx/), so let me take a deeper look into that and I'll get back to you.

**Comment by arctic-alpaca** [comment]
If I'm not mistaken, the current dockerfile in the repo doesn't work on ARM out of the box. This means most users probably build on x64 systems where buildx is part of the default docker installation as far as I can tell. 
I don't know how you currently provide the images on dockerhub, but I guess prebuilt ARM images would reduce the need to build themself for most users. For more advanced usecases, users probably need to work with the dockerfile itself anyway.

If keeping a buildx-free option is a priority, the buildx specific parts could probably be removed from the base dockerfile and a buildx compatible multi-architecture dockerfile could be added. This would allow users to build without buildx while enabling ARM images. Not sure what you think about more or less duplicating the dockerfile.

**Comment by iegomez** [comment]
@arctic-alpaca Thanks for the explanation, Docker is not my cup of tea and I'm a bit ignorant since I barely if ever use it. Images are currently built automatically for each release and on every push to master through Dockerhub's builds. I think we should be able to make it work with `buildx`: https://docs.docker.com/docker-hub/builds/#build-images-with-buildkit

So could you add some documentation about building for ARM and general usage of the modified Dockerfile to README.md? I'll then create a new build rule targeting a test branch to check if it works with Dockerhub.

**Comment by arctic-alpaca** [comment]
> So could you add some documentation about building for ARM and general usage of the modified Dockerfile to README.md?

Sure. Do you want the `/docker/README.md` and the corresponding dockerfile to be modified as well?

Regarding the builds, I have no experience with Dockerhub builds so I'm not sure I can assist if there are any issues there. For my own usage I created a [github actions workflow](https://github.com/arctic-alpaca/mosquitto-go-auth-multiarch/blob/main/.github/workflows/create_containers.yml) which allows building and pushing to Dockerhub for mosquitto v1.x and v2.x simultaneously without duplicating the dockerfile. [Github actions are free for public repositories](https://github.com/features/actions) if you want to take a look at it. Currently the workflow runs every day and uses the latest release from your repository, if you are interested, I could modify it for your current usage. To use the linked workflow, you need to supply a dockerhub username and token as described here:
* https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository
* https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-docker-hub Note: This guide uses the docker password which should be avoided. Use a token as described in the next links instead.
* https://github.com/marketplace/actions/docker-login
* https://docs.docker.com/docker-hub/access-tokens/

**Comment by iegomez** [comment]
Amazing! I'll take a look at those docs. 🙇

**Comment by iegomez** [comment]
> Sure. Do you want the /docker/README.md and the corresponding dockerfile to be modified as well?

Yeah, Docker duplication is ind of a mess, I think we should get rid of the `docker` dir and move docs to the root dir.

**Comment by arctic-alpaca** [comment]
I just realized a potential issue when working on the documentation. This Dockerfile currently assumes it's run on x86/amd64 and only cross-compiles containers for arm architectures. Native compilation on arm isn't tested and probably not supported in the current form. Sorry I didn't communicate this earlier.

**Comment by iegomez** [comment]
@arctic-alpaca No worries. 😉 

I was actually thinking that maybe the whole Docker infra could be moved out to a different repo since I'm usually not the one doing any Docker changes. We would lose Dockerhub integration that auto builds images on releases and pushes to master, but maybe Github actions could be leveraged to hook said events and trigger builds. That would also allow to have better organized and dedicated images for different platforms, mosquito versions, plugin releases, and so on.

So here comes the big question: would you be interested in building and maintaining such a repository? Maybe with the help of other contributors that have built the Docker support that exists today. 
If so, I'd remove everything Docker related from this repo and link to yours instead for Docker support. Besides some usage for a few months in a project which was deployed with K8s, and that was a while ago, I'm far from a Docker guy and don't really have the time or incentive at the moment to do a deep dive into it. It'd also remove the friction of me having to review PRs where I'm clearly the less informed party.

Let me know what you think.

Cheers!

**Comment by arctic-alpaca** [comment]
I'm sorry, I'm currently not in a position where I can commit to maintaining a repository. I'd be happy to help set it up though.  I hope I find the time to document this Dockerfile in the coming days. Sorry it's taking to long.

**Comment by iegomez** [comment]
Oh, no worries at all, @arctic-alpaca. I'm in a similar position, and currently only very slowly working on moving from `auth_opt` passed options to a proper plugin configuration file. It would make options documentation, parsing and usage and lot cleaner, but it's both a huge effort and big change for users. That'll probably end up being a 2.0 release in itself.

So I'm kind of taking a rest from anything else, which was probably true already when it comes to Docker support. Thus, I thought I'd ask since you mentioned you already had some Docker images building with Github actions going on, which could be enough and already better than what this repo offers Docker wise. So yeah, my question came out a bit too involved maybe 😅 , while really I was thinking I could link to your solution if it's publicly available, or ask if you would be willing to make it public, and get rid of the current Docker stuff. Only later (and only if possible, needed, etc.), it could be grown with contributions from others to support different platforms and all the shenanigans I mentioned. 

But again, no worries if you're not able to do so. Also, no rush at all on the current Dockerfile documentation. 😉 

Cheers!

File: README.md [hunk 1]
```diff
@@ -1466,11 +1466,40 @@ See the official [MQTT authentication & authorization guide](https://www.loraser
 
 ### Docker
 
-This project provides example Dockerfiles for building a Docker container that contains `mosquitto` and the `mosquitto-go-auth` plug-in.
+#### Support and issues
+Please be aware that, since Docker isn't actively used by the maintainer of this project, support for issues regarding Docker, the provided images and building Docker images in very limited.
```
Comment (iegomez) [inline README.md:1470]:
```suggestion
Please be aware that, since Docker isn't actively used by the maintainer of this project, support for issues regarding Docker, the provided images and building Docker images is very limited and usually driven by other contributors.
```

File: README.md [hunk 2]
```diff
@@ -1466,11 +1466,40 @@ See the official [MQTT authentication & authorization guide](https://www.loraser
 
 ### Docker
 
-This project provides example Dockerfiles for building a Docker container that contains `mosquitto` and the `mosquitto-go-auth` plug-in.
+#### Support and issues
+Please be aware that, since Docker isn't actively used by the maintainer of this project, support for issues regarding Docker, the provided images and building Docker images in very limited. 
 
-Please read the [documentation](./docker/README.md) in the [docker](/docker) directory for more information.
+#### Prebuilt images
```
Comment (iegomez) [inline README.md:1472]: Well, this will no longer be true 10 days from now, might as well just remove it.

**Comment by iegomez** [comment]
This is great, @arctic-alpaca, thank you very much! 

- Notice that https://github.com/iegomez/mosquitto-go-auth/pull/178 introduced a couple of conflicts, could you rebase from `master` to resolve them? I also wanted to ask you about `tini`, introduced in that PR: from what I read the addition made sense, but I might not be aware of some drawbacks.
- I'm in for Github Actions workflow and will gladly check said PR.
- Finally, an hour ago I got this email from Docker:

> Hi there, 
> 
> As one of the users of Docker Hub’s Autobuild service, we wanted to reach out and let you know that from June 18th, 2021 users on the free plan will no longer have access to the Autobuild feature. This means that any of your currently configured Autobuild will fail to run and you will need to upgrade to a Pro or Team account to restore functionality. You can read more about the changes on our blog. 
> 
> To ease this transition we are offering 20% off Docker Pro and Team for new and returning subscriptions through June 18, 2021 so you can continue using that Autobuild goodness you know and love. 
> 
> If you’re part of the Docker Open Source program, and currently leveraging Autobuilds as part of a Free plan, we want to continue supporting you and we will be reaching out to make sure you will not be impacted by this change. 
> 
> Docker is wholly focused on providing you amazing and magical experiences. We really appreciate your support and the community’s understanding as the whole industry battles against these abusive crypto miners. . 
> 
> Thanks, 
> 
> Team Docker 

I'm going through the application for the Docker Open Source program, I'll let you know if I get in. If it goes south, I'd plainly remove prebuilt images using Autobuild and rely on Actions instead.

**Comment by arctic-alpaca** [comment]
> I also wanted to ask you about tini, introduced in that PR: from what I read the addition made sense, but I might not be aware of some drawbacks.

I hadn't heard of `tini` before, but it seems to make sense. Since this is one of the first few sentences on the project page, I wouldn't expect problems: `Docker images that work without Tini will work with Tini without any changes.`

> I'm in for Github Actions workflow and will gladly check said PR.

Great, I'll get on it as soon as I can!

> Finally, an hour ago I got this email from Docker:
...
> I'm going through the application for the Docker Open Source program, I'll let you know if I get in. If it goes south, I'd plainly remove prebuilt images using Autobuild and rely on Actions instead.

I wish you the best of luck! 
I'm not sure how having both autobuilding services enabled would work, I guess you would need to decide for one or use different DockerHub repositories.

**Review by iegomez — APPROVED** [review]

**Comment by arctic-alpaca** [comment]
While working on the Github actions workflow, I noticed an issue with the ARMv6 builds. This should be fixed now but I can't verify any builds besides x86_64/AMD64 and ARMv7 due to missing hardware. I added a line to the disclaimer explaining this.

**Comment by iegomez** [comment]
> While working on the Github actions workflow, I noticed an issue with the ARMv6 builds. This should be fixed now but I can't verify any builds besides x86_64/AMD64 and ARMv7 due to missing hardware. I added a line to the disclaimer explaining this.

I think that's fine for now, we'll surely hear about it if anyone tries it in said platforms and encounters an issue, so better to have it in to know.

Do you think this is ready to be merged now?

**Comment by arctic-alpaca** [comment]
> Do you think this is ready to be merged now?

As far as I can tell, everything is working as expected. I think this is ready now.

**Comment by iegomez** [comment]
Ok then, in it goes.
